# Generated by Django 5.2.4 on 2025-07-20 08:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('serial', models.CharField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('height', models.FloatField()),
                ('home_distance', models.FloatField()),
                ('horizontal_speed', models.FloatField()),
                ('vertical_speed', models.FloatField()),
                ('latitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('longitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DroneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(editable=False)),
                ('timestamp', models.DateTimeField(editable=False)),
                ('drone', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tracker.drone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
