# Generated by Django 5.2.4 on 2025-07-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronelog',
            name='payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='dronelog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
