# Generated by Django 5.2.4 on 2025-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_dronelog_payload_alter_dronelog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='is_online',
        ),
    ]
